[package]
name = "keygen"
version = "0.1.0"
authors = ["Xuming Zeng <xsznix@gmail.com>"]

[dependencies]
rand = "0.7.3"
getopts = "0.2.21"
rayon = "1.3.1"
num_cpus = "1.13.0"

[profile.dev]
opt-level = 3
debug = true

[profile.release]
lto = "fat"
codegen-units = 1
